### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by AsciiWolf** [ilyazzz/LACT#11]
Thanks for making this useful app! I think it would be great if this app could be packaged as a [Flatpak](https://flatpak.org) and published on [Flathub](https://flathub.org). :-)

**Comment by ilyazzz** [comment]
I'm not sure if it's possible, since LACT requires a background daemon running as root, and don't know if flatpak allows for such usage.
An appimage with a distro-agnostic install script would be possible, but it would still require things like the service to be installed separately, so it's still not a "single-file, self-contained application" scenario like it can be with standalone GUI apps.

I think making deb/rpm packages is a better approach for this kind of applications.

**Comment by eszlari** [comment]
A Flatpak version might be possible:

1. First you need to build the daemon as a separate, fully statically linked binary.
2. Flatpak allows you to run commands on the host system from inside the sandbox like this:

```
flatpak-run --host <COMMAND>
```

3. You could add a button to the GUI that says something like "Install & enable daemon on host system".
4. This button would execute the following commands:

```
flatpak-run --host pkexec install -Dm755 $DIR/lactd /usr/local/bin/lactd
flatpak-run --host pkexec install -Dm644 $DIR/lactd.service /etc/systemd/systemd/lactd.service
flatpak-run --host pkexec systemctl enable --now lactd
```
The path to the files from the Flatpak installation data ($DIR) can be found in the file `/.flatpak-info` inside the sandbox.

**Comment by ilya-zlobintsev** [comment]
> A Flatpak version might be possible:
> 
>     1. First you need to build the daemon as a separate, fully statically linked binary.
> 
>     2. Flatpak allows you to run commands on the host system from inside the sandbox like this:
> 
> 
> ```
> flatpak-run --host <COMMAND>
> ```
> 
> (needs the permission `--talk-name=org.freedesktop.Flatpak`)
> 
>     3. You could add a button to the GUI that says something like "Install & enable daemon on host system".
> 
>     4. This button would execute the following commands:
> 
> 
> ```
> flatpak-run --host pkexec install -Dm755 $DIR/lactd /usr/local/bin/lactd
> flatpak-run --host pkexec install -Dm644 $DIR/lactd.service /etc/systemd/systemd/lactd.service
> flatpak-run --host pkexec systemctl enable --now lactd
> ```
> 
> The path to the files from the Flatpak installation data ($DIR) can be found in the file `/.flatpak-info` inside the sandbox.

I initially rejected the idea of having the GUI and daemon parts being installed separately due to the installation process being convoluted, but if it could be automated like this, then maybe Flatpak isn't impossible after all.

However, there are some potential problems with this:
- Will the daemon have to be reinstalled every time the GUI Flatpak is updated?
- If the user uninstalls the Flatpak, there will still be a daemon leftover
- Will the users understand that while they installed a Flatpak, in reality it's going to run an install script affecting the host system?

And probably the most important question: is there demand for it, when it's not a "proper" self-sufficient Flatpak application? There is a way to easily generate native packages for different distros now with pkger, with the only limitation being that the distro has the required dependencies (mainly gtk4). Are there many people that want to use LACT and happen to run a distro older than Ubuntu 22.04 or a semi-recent version of Fedora?

**Comment by AsciiWolf** [comment]
Installing files into a system using `flatpak-run --host` is a very bad and dangerous idea, at least in my opinion.

**Comment by eszlari** [comment]
If you don't need systemd, you could run the daemon directly without installing:

```
flatpak-run --host pkexec $DIR/lactd
```

(see https://github.com/flathub/org.wireshark.Wireshark/issues/4#issuecomment-480993046)

**Comment by AsciiWolf** [comment]
That is a much better solution, thanks!

**Comment by ilya-zlobintsev** [comment]
> If you don't need systemd, you could run the daemon directly without installing:
> 
> ```
> flatpak-run --host pkexec $DIR/lactd
> ```
> 
> (see [flathub/org.wireshark.Wireshark#4 (comment)](https://github.com/flathub/org.wireshark.Wireshark/issues/4#issuecomment-480993046))

The problem with this is that the process either:
- Runs as a chlid process of the GUI, which means it exists when the GUI closes. This makes it pretty useless for fan control, and goes against the whole idea of why there is a daemon.
- Gets detached and runs separately. This means that there is no lifecycle management of any kind as it's not a systemd service, with no way to restart it or even stop it outside of finding and killing the process manually.

**Comment by eszlari** [comment]
How about creating a link to the `.service` file:

```
flatpak-run --host pkexec systemctl enable /var/lib/flatpak/app/com.domain.LACT/current/active/files/lactd.service
```
https://unix.stackexchange.com/questions/271541/enabling-linked-unit-files-in-systemd
