### ISSUE TITLE
Killing the lact-daemon

### ISSUE THREAD

**Issue by ShketRybee** [ilyazzz/LACT#17]
After killing lact-daemon fan speed increases somewhere to 60 percents. The same thing happens for one second when you turn off the computer.

**Comment by ilyazzz** [comment]
When the daemon shuts down, it turns fan control back to "automatic" (controlled by the driver). Due to a kernel bug this is not handled properly on all GPUs, and unfortunately there is nothing I can do about it. Not switching fan control to automatic is also not an option, since that would leave with no fan control at all after daemon shutdown.

If you want to be able to shut the daemon down without the fan speed bugging out, don't use the fan control feature.
