### ISSUE TITLE
Use /sys to determine if overclocking is enabled

### ISSUE THREAD

**Issue by nikitalita** [ilyazzz/LACT#28]
Right now LACT just checks to see if `amdgpu.ppfeaturemask` is set at all in the grub config to determine if overclocking is enabled. Instead, get the ppfeaturemask value from `/sys/module/amdgpu/parameters/ppfeaturemask` and check `ppfeaturemask & 0x4000`  to determine if overclocking is enabled.

`0x4000` is the `PP_OVERDRIVE_MASK`, see [amd_shared.h](https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/amd/include/amd_shared.h#L211).

**Comment by ilyazzz** [comment]
This sounds like a better solution, but what exactly should I be checking for in that file? If I understand it correctly, it's possible to selectively enable driver features with the mask, but how do I check that specifically the overdrive table is enabled?

Are the features "incremental" (so that enabling a feature at a given number enables all the previous ones), in which case I should be just checking if the value is at least `0x4000`?

**Comment by nikitalita** [comment]
The file is just the mask value in decimal. The enum values are bitmasks; basically, you can check which is enabled by doing a bitwise & on the mask value with the enum value. `ppfeaturemask & PP_STUTTER_MODE ` would check if stutter mode is enabled, for example.

**Comment by nikitalita** [comment]
Also, I don't think it's possible to enable PP features while the module is installed; you'd have to set the value in `/etc/modprobe.d/amdgpu.conf` and then reinstall the module (which I suppose would necessitate a restart, and probably regenerating the initramfs).

**Comment by ilyazzz** [comment]
@nikitalita I've implemented it [here](https://github.com/ilyazzz/LACT/pull/29) and it seems to work correctly, if it also works for you I'll merge it.

**Comment by nikitalita** [comment]
yup, that works!
